name: Guardian Scraper Hourly

on:
  push:                     # Executa ao fazer push
  workflow_dispatch:        # Permite execução manual
  schedule:
    - cron: '0 * * * *'     # Executa todos os dias à hora certa

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # Permite fazer commits no repositório

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests

      - name: Correr scraper
        env:
          GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}
        run: python guardian_scraper.py

      - name: Ver conteúdo da pasta
        run: ls -R

      - name: Guardar artigos
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "Artigos recolhidos automaticamente"
          add: 'artigos/*.json'
