name: Guardian Scraper Hourly

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 👈 Isto permite fazer commit e push

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests

      - name: Correr scraper
        env:
          GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}
        run: python guardian_scraper.py

      - name: Guardar artigos
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "Artigos recolhidos automaticamente"
          add: 'artigos/*.json logs/*.log'
